// ============================================================
// Language Context — FR/EN Toggle
// ERP Integrated Business Simulator — Collège de la Concorde
// ============================================================
import React, { createContext, useContext, useState } from 'react';

export type Language = 'fr' | 'en';

interface LanguageContextType {
  lang: Language;
  setLang: (l: Language) => void;
  t: (key: string) => string;
}

const translations: Record<string, Record<Language, string>> = {
  // Navigation
  'nav.dashboard': { fr: 'Tableau de bord', en: 'Dashboard' },
  'nav.modules': { fr: 'Modules ERP', en: 'ERP Modules' },
  'nav.simulator': { fr: 'Simulateur', en: 'Simulator' },
  'nav.cohorts': { fr: 'Cohortes', en: 'Cohorts' },
  'nav.assignments': { fr: 'Travaux', en: 'Assignments' },
  'nav.monitoring': { fr: 'Suivi', en: 'Monitoring' },
  'nav.teacherGuide': { fr: 'Guide Professeur', en: 'Teacher Guide' },
  'nav.admin': { fr: 'Administration', en: 'Administration' },
  'nav.logout': { fr: 'Déconnexion', en: 'Logout' },
  // Dashboard
  'dashboard.greeting': { fr: 'Bonjour', en: 'Hello' },
  'dashboard.subtitle.teacher': { fr: 'Tableau de bord professeur — ERP Integrated Business Simulator', en: 'Teacher Dashboard — ERP Integrated Business Simulator' },
  'dashboard.subtitle.student': { fr: 'Tableau de bord étudiant — ERP Integrated Business Simulator', en: 'Student Dashboard — ERP Integrated Business Simulator' },
  'dashboard.subtitle.admin': { fr: 'Tableau de bord administrateur — ERP Integrated Business Simulator', en: 'Admin Dashboard — ERP Integrated Business Simulator' },
  'dashboard.modules': { fr: 'Modules ERP', en: 'ERP Modules' },
  'dashboard.scenarios': { fr: 'Scénarios', en: 'Scenarios' },
  'dashboard.students': { fr: 'Étudiants', en: 'Students' },
  'dashboard.hours': { fr: 'Heures de formation', en: 'Training Hours' },
  'dashboard.progress': { fr: 'Progression globale', en: 'Overall Progress' },
  'dashboard.recentActivity': { fr: 'Activité récente', en: 'Recent Activity' },
  'dashboard.moduleProgress': { fr: 'Progression par module', en: 'Module Progress' },
  'dashboard.quickAccess': { fr: 'Accès rapide', en: 'Quick Access' },
  'dashboard.startSimulator': { fr: 'Démarrer le simulateur', en: 'Start Simulator' },
  'dashboard.viewModules': { fr: 'Voir les modules', en: 'View Modules' },
  'dashboard.viewMonitoring': { fr: 'Voir le suivi', en: 'View Monitoring' },
  // Modules
  'modules.title': { fr: 'Modules ERP', en: 'ERP Modules' },
  'modules.subtitle': { fr: 'Programme 2 — 30 heures · SAP S/4HANA · Dynamics 365 · Odoo', en: 'Programme 2 — 30 hours · SAP S/4HANA · Dynamics 365 · Odoo' },
  'modules.slides': { fr: 'Slides', en: 'Slides' },
  'modules.scenarios': { fr: 'Scénarios', en: 'Scenarios' },
  'modules.hours': { fr: 'heures', en: 'hours' },
  'modules.start': { fr: 'Commencer', en: 'Start' },
  'modules.continue': { fr: 'Continuer', en: 'Continue' },
  // Simulator
  'sim.title': { fr: 'Simulateur ERP', en: 'ERP Simulator' },
  'sim.start': { fr: 'Démarrer la simulation', en: 'Start Simulation' },
  'sim.next': { fr: 'Étape suivante', en: 'Next Step' },
  'sim.prev': { fr: 'Précédent', en: 'Previous' },
  'sim.hint': { fr: 'Indice', en: 'Hint' },
  'sim.validate': { fr: 'Valider', en: 'Validate' },
  'sim.complete': { fr: 'Simulation terminée', en: 'Simulation Complete' },
  'sim.score': { fr: 'Score final', en: 'Final Score' },
  'sim.chooseSystem': { fr: 'Choisir le système ERP', en: 'Choose ERP System' },
  'sim.objective': { fr: 'Objectif pédagogique', en: 'Learning Objective' },
  'sim.steps': { fr: 'Étapes du scénario', en: 'Scenario Steps' },
  'sim.elapsed': { fr: 'Temps écoulé', en: 'Elapsed Time' },
  'sim.progression': { fr: 'Progression', en: 'Progress' },
  'sim.beginner': { fr: 'Débutant', en: 'Beginner' },
  'sim.intermediate': { fr: 'Intermédiaire', en: 'Intermediate' },
  'sim.advanced': { fr: 'Avancé', en: 'Advanced' },
  // Slides
  'slides.keyPoints': { fr: 'Points clés', en: 'Key Points' },
  'slides.systemRef': { fr: 'Référence dans les systèmes ERP', en: 'Reference in ERP Systems' },
  'slides.prev': { fr: 'Précédent', en: 'Previous' },
  'slides.next': { fr: 'Suivant', en: 'Next' },
  'slides.present': { fr: 'Mode présentation', en: 'Presentation Mode' },
  'slides.exitPresent': { fr: 'Quitter la présentation', en: 'Exit Presentation' },
  'slides.quiz': { fr: 'Quiz', en: 'Quiz' },
  'slides.quizTitle': { fr: 'Quiz de compréhension', en: 'Comprehension Quiz' },
  'slides.quizSubtitle': { fr: 'Testez vos connaissances sur ce module', en: 'Test your knowledge on this module' },
  'slides.quizCorrect': { fr: 'Bonne réponse !', en: 'Correct!' },
  'slides.quizWrong': { fr: 'Mauvaise réponse', en: 'Wrong answer' },
  'slides.quizExplanation': { fr: 'Explication', en: 'Explanation' },
  'slides.quizNext': { fr: 'Question suivante', en: 'Next Question' },
  'slides.quizFinish': { fr: 'Terminer le quiz', en: 'Finish Quiz' },
  'slides.quizResult': { fr: 'Résultat du quiz', en: 'Quiz Result' },
  'slides.quizRetry': { fr: 'Recommencer', en: 'Retry' },
  'slides.quizContinue': { fr: 'Continuer vers les scénarios', en: 'Continue to Scenarios' },
  // Teacher Guide
  'guide.title': { fr: 'Guide du Professeur', en: 'Teacher Guide' },
  'guide.exportPDF': { fr: 'Exporter en PDF', en: 'Export PDF' },
  'guide.exportPDFShort': { fr: 'PDF', en: 'PDF' },
  'guide.totalHours': { fr: 'Durée totale', en: 'Total Duration' },
  'guide.modules': { fr: 'Modules', en: 'Modules' },
  'guide.scenarios': { fr: 'Scénarios', en: 'Scenarios' },
  'guide.systems': { fr: 'Systèmes ERP', en: 'ERP Systems' },
  // Monitoring
  'monitoring.title': { fr: 'Suivi des étudiants', en: 'Student Monitoring' },
  'monitoring.activeStudents': { fr: 'Étudiants actifs', en: 'Active Students' },
  'monitoring.avgScore': { fr: 'Score moyen', en: 'Average Score' },
  'monitoring.avgCompletion': { fr: 'Complétion moyenne', en: 'Avg. Completion' },
  'monitoring.availableScenarios': { fr: 'Scénarios disponibles', en: 'Available Scenarios' },
  'monitoring.completionByModule': { fr: 'Complétion par module', en: 'Completion by Module' },
  'monitoring.studentDetail': { fr: 'Détail par étudiant', en: 'Student Detail' },
  // Login
  'login.title': { fr: 'Connexion', en: 'Login' },
  'login.subtitle': { fr: 'Accédez à votre environnement ERP simulé', en: 'Access your simulated ERP environment' },
  'login.email': { fr: 'Adresse courriel', en: 'Email Address' },
  'login.password': { fr: 'Mot de passe', en: 'Password' },
  'login.button': { fr: 'Se connecter', en: 'Sign In' },
  'login.demoAccess': { fr: 'Accès de démonstration', en: 'Demo Access' },
  'login.system': { fr: 'Système ERP de référence', en: 'Reference ERP System' },
  // Common
  'common.programme': { fr: 'Programme 2 — ERP', en: 'Programme 2 — ERP' },
  'common.hours': { fr: '30 heures', en: '30 hours' },
  'common.modules_count': { fr: '5 modules', en: '5 modules' },
  'common.back': { fr: 'Retour', en: 'Back' },
  'common.save': { fr: 'Enregistrer', en: 'Save' },
  'common.cancel': { fr: 'Annuler', en: 'Cancel' },
  'common.simulate': { fr: 'Simuler', en: 'Simulate' },
  'common.restart': { fr: 'Recommencer', en: 'Restart' },
  'common.completed': { fr: 'Complété', en: 'Completed' },
  'common.active': { fr: 'Actif', en: 'Active' },
  'common.inactive': { fr: 'Inactif', en: 'Inactive' },
  'common.planned': { fr: 'Planifié', en: 'Planned' },
  'common.pending': { fr: 'En attente', en: 'Pending' },
  'common.delete': { fr: 'Supprimer', en: 'Delete' },
  'common.edit': { fr: 'Modifier', en: 'Edit' },
  'common.add': { fr: 'Ajouter', en: 'Add' },
  'common.create': { fr: 'Créer', en: 'Create' },
  'common.import': { fr: 'Importer', en: 'Import' },
  'common.export': { fr: 'Exporter', en: 'Export' },
  'common.search': { fr: 'Rechercher', en: 'Search' },
  'common.noData': { fr: 'Aucune donnée', en: 'No data' },
  'common.loading': { fr: 'Chargement...', en: 'Loading...' },
  'common.error': { fr: 'Erreur', en: 'Error' },
  'common.success': { fr: 'Succès', en: 'Success' },
  'common.confirm': { fr: 'Confirmer', en: 'Confirm' },
  'common.close': { fr: 'Fermer', en: 'Close' },
  'common.view': { fr: 'Voir', en: 'View' },
  'common.never': { fr: 'Jamais', en: 'Never' },
  'common.yes': { fr: 'Oui', en: 'Yes' },
  'common.no': { fr: 'Non', en: 'No' },
  'common.total': { fr: 'Total', en: 'Total' },
  'common.average': { fr: 'Moyenne', en: 'Average' },
  'common.score': { fr: 'Score', en: 'Score' },
  'common.attempts': { fr: 'Tentatives', en: 'Attempts' },
  'common.students': { fr: 'Étudiants', en: 'Students' },
  'common.cohort': { fr: 'Cohorte', en: 'Cohort' },
  'common.cohorts': { fr: 'Cohortes', en: 'Cohorts' },
  'common.scenarios': { fr: 'Scénarios', en: 'Scenarios' },
  'common.module': { fr: 'Module', en: 'Module' },
  'common.modules': { fr: 'Modules', en: 'Modules' },
  'common.program': { fr: 'Programme', en: 'Program' },
  'common.semester': { fr: 'Semestre', en: 'Semester' },
  'common.year': { fr: 'Année', en: 'Year' },
  'common.status': { fr: 'Statut', en: 'Status' },
  'common.name': { fr: 'Nom', en: 'Name' },
  'common.email': { fr: 'Email', en: 'Email' },
  'common.notes': { fr: 'Notes', en: 'Notes' },
  'common.password': { fr: 'Mot de passe', en: 'Password' },
  'common.actions': { fr: 'Actions', en: 'Actions' },
  'common.details': { fr: 'Détails', en: 'Details' },
  'common.profile': { fr: 'Profil', en: 'Profile' },
  'common.results': { fr: 'Résultats', en: 'Results' },
  'common.history': { fr: 'Historique', en: 'History' },
  'common.duration': { fr: 'Durée', en: 'Duration' },
  'common.difficulty': { fr: 'Difficulté', en: 'Difficulty' },
  'common.deadline': { fr: 'Échéance', en: 'Deadline' },
  'common.lastActive': { fr: 'Dernière activité', en: 'Last Active' },
  'common.noActivity': { fr: 'Aucune activité', en: 'No activity' },
  'common.seeSlides': { fr: 'Voir les slides', en: 'View Slides' },
  'common.simulate': { fr: 'Simuler', en: 'Simulate' },
  'common.seeAll': { fr: 'Voir tout', en: 'View all' },
  'common.completedCount': { fr: 'complétés', en: 'completed' },
  'common.onSimulations': { fr: 'sur les simulations', en: 'on simulations' },
  'common.atRisk': { fr: 'En risque', en: 'At Risk' },
  'common.improving': { fr: 'En progression', en: 'Improving' },
  'common.confirmDelete': { fr: 'Confirmer la suppression', en: 'Confirm Deletion' },
  'common.irreversible': { fr: 'Cette action est irréversible.', en: 'This action is irreversible.' },
  'common.instantAgo': { fr: "À l'instant", en: 'Just now' },
  'common.minutesAgo': { fr: 'Il y a {n}min', en: '{n}min ago' },
  'common.hoursAgo': { fr: 'Il y a {n}h', en: '{n}h ago' },
  'common.daysAgo': { fr: 'Il y a {n}j', en: '{n}d ago' },
  // Login extended
  'login.student': { fr: 'Étudiant', en: 'Student' },
  'login.teacher': { fr: 'Professeur', en: 'Teacher' },
  'login.connecting': { fr: 'Connexion...', en: 'Signing in...' },
  'login.demoStudent': { fr: 'Démo étudiant', en: 'Demo Student' },
  'login.demoTeacher': { fr: 'Démo professeur', en: 'Demo Teacher' },
  'login.accountCreated': { fr: 'Votre compte est créé par votre professeur.', en: 'Your account is created by your teacher.' },
  'login.autoFill': { fr: 'Remplissage automatique des identifiants de démo', en: 'Auto-fill demo credentials' },
  'login.tabStudent': { fr: 'Étudiant', en: 'Student' },
  'login.tabTeacher': { fr: 'Professeur', en: 'Teacher' },
  'login.emailLabel': { fr: 'Adresse email', en: 'Email address' },
  'login.passwordLabel': { fr: 'Mot de passe', en: 'Password' },
  'login.submit': { fr: 'Se connecter', en: 'Sign In' },
  'login.demoHint': { fr: 'Remplissage automatique des identifiants de démo', en: 'Auto-fill demo credentials' },
  'login.accountCreatedBy': { fr: 'Votre compte est créé par votre professeur.', en: 'Your account is created by your teacher.' },
  'login.successToast': { fr: 'Connexion réussie', en: 'Login successful' },
  'login.errorCredentials': { fr: 'Email ou mot de passe incorrect.', en: 'Incorrect email or password.' },
  // Monitoring extended
  'monitoring.controlTower': { fr: 'Tour de contrôle pédagogique', en: 'Pedagogical Control Tower' },
  'monitoring.realtime': { fr: 'Suivi en temps réel', en: 'Real-time monitoring' },
  'monitoring.attempts': { fr: 'tentatives enregistrées', en: 'attempts recorded' },
  'monitoring.exportCSV': { fr: 'Exporter CSV', en: 'Export CSV' },
  'monitoring.tabStudents': { fr: 'Étudiants', en: 'Students' },
  'monitoring.tabCohorts': { fr: 'Cohortes', en: 'Cohorts' },
  'monitoring.tabInsights': { fr: 'Insights pédagogiques', en: 'Pedagogical Insights' },
  'monitoring.noAttempts': { fr: 'Aucune tentative enregistrée', en: 'No attempts recorded' },
  'monitoring.noStudents': { fr: 'Aucun étudiant trouvé', en: 'No students found' },
  'monitoring.atRisk': { fr: 'En risque', en: 'At Risk' },
  'monitoring.regressing': { fr: 'Régresse', en: 'Regressing' },
  'monitoring.stable': { fr: 'Stable', en: 'Stable' },
  'monitoring.new': { fr: 'Nouveau', en: 'New' },
  'monitoring.filterAll': { fr: 'Tous', en: 'All' },
  'monitoring.filterAtRisk': { fr: 'En risque', en: 'At Risk' },
  'monitoring.filterImproving': { fr: 'En progression', en: 'Improving' },
  'monitoring.sortName': { fr: 'Nom', en: 'Name' },
  'monitoring.sortScore': { fr: 'Score', en: 'Score' },
  'monitoring.sortAttempts': { fr: 'Tentatives', en: 'Attempts' },
  'monitoring.sortLastActive': { fr: 'Activité', en: 'Activity' },
  'monitoring.avgScore': { fr: 'Score moyen', en: 'Average Score' },
  'monitoring.bestScore': { fr: 'Meilleur score', en: 'Best Score' },
  'monitoring.learnerProfile': { fr: "Profil d'apprentissage", en: 'Learner Profile' },
  'monitoring.erpDiagnostic': { fr: 'Diagnostic ERP', en: 'ERP Diagnostic' },
  'monitoring.erpDiagnosticClass': { fr: 'Diagnostic ERP — classe', en: 'ERP Diagnostic — class' },
  'monitoring.attemptHistory': { fr: 'Historique des tentatives', en: 'Attempt History' },
  'monitoring.teacherActions': { fr: 'Actions pédagogiques', en: 'Pedagogical Actions' },
  'monitoring.reviewSlides': { fr: 'Revoir les slides', en: 'Review Slides' },
  'monitoring.retryGuided': { fr: 'Retenter en mode guidé', en: 'Retry in Guided Mode' },
  'monitoring.sendFeedback': { fr: 'Envoyer un feedback', en: 'Send Feedback' },
  'monitoring.hintsPerAttempt': { fr: 'indices/tentative', en: 'hints/attempt' },
  'monitoring.understands': { fr: 'Comprend le processus', en: 'Understands the process' },
  'monitoring.confusesNames': { fr: 'Confond les noms ERP', en: 'Confuses ERP names' },
  'monitoring.confusesProcess': { fr: 'Confond le processus', en: 'Confuses the process' },
  'monitoring.doubleConfusion': { fr: 'Double confusion', en: 'Double confusion' },
  'monitoring.clickForDiag': { fr: 'Cliquez sur un étudiant dans l\'onglet « Étudiants » pour voir son diagnostic individuel.', en: 'Click a student in the "Students" tab to view their individual diagnostic.' },
  'monitoring.profileDistrib': { fr: "Distribution des profils d'apprentissage", en: 'Learner Profile Distribution' },
  'monitoring.moduleDifficulty': { fr: 'Difficulté par module', en: 'Module Difficulty' },
  'monitoring.cohortOverview': { fr: 'Vue par cohorte', en: 'Cohort Overview' },
  'monitoring.noData': { fr: 'Aucune tentative enregistrée', en: 'No attempts recorded' },
  'monitoring.totalErrors': { fr: 'erreur(s) totales', en: 'total error(s)' },
  'monitoring.hintsUsed': { fr: 'indice(s) utilisé(s)', en: 'hint(s) used' },
  'monitoring.diagTermConf': { fr: 'Cet étudiant commet beaucoup d\'erreurs mais finit par réussir. Il comprend le processus métier mais confond les noms ERP (T-codes, menus). Recommandation : exercices de mémorisation de la terminologie.', en: 'This student makes many errors but eventually succeeds. They understand the business process but confuse ERP names (T-codes, menus). Recommendation: terminology memorization exercises.' },
  'monitoring.diagProcConf': { fr: 'Cet étudiant utilise beaucoup d\'indices et obtient un score faible. Il ne comprend pas encore la logique du processus métier. Recommandation : revoir les slides du module et refaire le scénario en mode guidé.', en: 'This student uses many hints and scores low. They do not yet understand the business process logic. Recommendation: review module slides and redo the scenario in guided mode.' },
  'monitoring.diagBothConf': { fr: 'Double confusion : terminologie ERP et logique de processus. Recommandation : session individuelle avec le professeur avant de continuer.', en: 'Double confusion: ERP terminology and process logic. Recommendation: individual session with the teacher before continuing.' },
  'monitoring.diagOk': { fr: 'L\'étudiant distingue correctement le processus métier de la terminologie ERP. Aucune intervention nécessaire.', en: 'The student correctly distinguishes the business process from ERP terminology. No intervention needed.' },
  // Learner profiles
  'profile.precise': { fr: 'Exécuteur précis', en: 'Precise Executor' },
  'profile.reliable': { fr: 'Apprenant fiable', en: 'Reliable Learner' },
  'profile.fast': { fr: 'Rapide mais imprécis', en: 'Fast but Imprecise' },
  'profile.guided': { fr: 'Guidé en progression', en: 'Guided Progress' },
  'profile.support': { fr: 'Nécessite du soutien', en: 'Needs Support' },
  // Confusion signals
  'confusion.noData': { fr: 'Pas de données', en: 'No data' },
  'confusion.termConf': { fr: 'Confond les noms ERP', en: 'Confuses ERP names' },
  'confusion.procConf': { fr: 'Confond le processus', en: 'Confuses the process' },
  'confusion.bothConf': { fr: 'Confusion terminologie + processus', en: 'Terminology + process confusion' },
  'confusion.ok': { fr: 'Comprend le processus', en: 'Understands the process' },
  // Cohorts page
  'cohorts.title': { fr: 'Gestion des cohortes', en: 'Cohort Management' },
  'cohorts.subtitle': { fr: 'Gérez vos groupes d\'étudiants — Programme 2 ERP', en: 'Manage your student groups — Programme 2 ERP' },
  'cohorts.newCohort': { fr: 'Nouvelle cohorte', en: 'New Cohort' },
  'cohorts.importCSV': { fr: 'Importer CSV', en: 'Import CSV' },
  'cohorts.activeCohorts': { fr: 'Cohortes actives', en: 'Active Cohorts' },
  'cohorts.totalStudents': { fr: 'Étudiants total', en: 'Total Students' },
  'cohorts.activeStudents': { fr: 'Étudiants actifs', en: 'Active Students' },
  'cohorts.activityRate': { fr: "Taux d'activité", en: 'Activity Rate' },
  'cohorts.searchPlaceholder': { fr: 'Rechercher un étudiant par nom ou email...', en: 'Search student by name or email...' },
  'cohorts.results': { fr: 'résultat(s) pour', en: 'result(s) for' },
  'cohorts.noStudentFound': { fr: 'Aucun étudiant trouvé', en: 'No student found' },
  'cohorts.noCohort': { fr: 'Aucune cohorte. Créez votre première cohorte.', en: 'No cohort. Create your first cohort.' },
  'cohorts.noStudentInCohort': { fr: 'Aucun étudiant dans cette cohorte.', en: 'No students in this cohort.' },
  'cohorts.addFirst': { fr: '+ Ajouter le premier étudiant', en: '+ Add the first student' },
  'cohorts.addStudent': { fr: 'Ajouter', en: 'Add' },
  'cohorts.students': { fr: 'Étudiants', en: 'Students' },
  'cohorts.actives': { fr: 'Actifs', en: 'Active' },
  'cohorts.inactives': { fr: 'Inactifs', en: 'Inactive' },
  'cohorts.confirmDeleteStudent': { fr: 'Supprimer l\'étudiant "{name}" ? Cette action est irréversible.', en: 'Delete student "{name}"? This action is irreversible.' },
  'cohorts.confirmDeleteCohort': { fr: 'Supprimer la cohorte "{name}" ? Les étudiants associés ne seront pas supprimés.', en: 'Delete cohort "{name}"? Associated students will not be deleted.' },
  'cohorts.csvPreviewTitle': { fr: "Aperçu de l'import", en: 'Import Preview' },
  'cohorts.csvValid': { fr: 'valide(s)', en: 'valid' },
  'cohorts.csvIgnored': { fr: 'ignoré(s)', en: 'ignored' },
  'cohorts.csvDefaultPwd': { fr: 'Mot de passe par défaut :', en: 'Default password:' },
  'cohorts.csvChangePwd': { fr: 'à changer lors de la première connexion', en: 'to be changed on first login' },
  'cohorts.csvFormat': { fr: 'Format attendu :', en: 'Expected format:' },
  'cohorts.csvFormatDesc': { fr: 'une ligne par étudiant', en: 'one line per student' },
  'cohorts.importBtn': { fr: 'Importer {n} étudiant(s)', en: 'Import {n} student(s)' },
  'cohorts.newStudentTitle': { fr: 'Ajouter un étudiant', en: 'Add a Student' },
  'cohorts.editStudentTitle': { fr: "Modifier l'étudiant", en: 'Edit Student' },
  'cohorts.fullName': { fr: 'Nom complet *', en: 'Full Name *' },
  'cohorts.emailField': { fr: 'Adresse email *', en: 'Email Address *' },
  'cohorts.passwordField': { fr: 'Mot de passe *', en: 'Password *' },
  'cohorts.newPasswordField': { fr: 'Nouveau mot de passe (laisser vide pour ne pas changer)', en: 'New password (leave blank to keep unchanged)' },
  'cohorts.cohortField': { fr: 'Cohorte', en: 'Cohort' },
  'cohorts.noCohortOption': { fr: '— Aucune cohorte —', en: '— No cohort —' },
  'cohorts.statusField': { fr: 'Statut', en: 'Status' },
  'cohorts.notesField': { fr: 'Notes (optionnel)', en: 'Notes (optional)' },
  'cohorts.newCohortTitle': { fr: 'Nouvelle cohorte', en: 'New Cohort' },
  'cohorts.editCohortTitle': { fr: 'Modifier la cohorte', en: 'Edit Cohort' },
  'cohorts.lastActivity': { fr: 'dernière activité', en: 'last activity' },
  // --- new cohorts keys (v2.1 bilingual rewrite) ---
  'cohorts.active': { fr: 'Actif', en: 'Active' },
  'cohorts.inactive': { fr: 'Inactif', en: 'Inactive' },
  'cohorts.planned': { fr: 'Planifié', en: 'Planned' },
  'cohorts.completed': { fr: 'Complété', en: 'Completed' },
  'cohorts.status': { fr: 'Statut', en: 'Status' },
  'cohorts.cohort': { fr: 'Cohorte', en: 'Cohort' },
  'cohorts.cohortName': { fr: 'Nom de la cohorte', en: 'Cohort Name' },
  'cohorts.description': { fr: 'Description', en: 'Description' },
  'cohorts.semester': { fr: 'Semestre', en: 'Semester' },
  'cohorts.year': { fr: 'Année', en: 'Year' },
  'cohorts.fall': { fr: 'Automne', en: 'Fall' },
  'cohorts.winter': { fr: 'Hiver', en: 'Winter' },
  'cohorts.summer': { fr: 'Été', en: 'Summer' },
  'cohorts.addStudent': { fr: 'Ajouter un étudiant', en: 'Add Student' },
  'cohorts.editStudent': { fr: "Modifier l'étudiant", en: 'Edit Student' },
  'cohorts.editCohort': { fr: 'Modifier la cohorte', en: 'Edit Cohort' },
  'cohorts.fullName': { fr: 'Nom complet', en: 'Full Name' },
  'cohorts.emailAddress': { fr: 'Adresse email', en: 'Email Address' },
  'cohorts.password': { fr: 'Mot de passe', en: 'Password' },
  'cohorts.newPasswordOptional': { fr: 'Nouveau mot de passe (laisser vide pour ne pas changer)', en: 'New password (leave blank to keep unchanged)' },
  'cohorts.passwordMin': { fr: 'Min. 6 caractères', en: 'Min. 6 characters' },
  'cohorts.noCohort': { fr: 'Aucune cohorte', en: 'No cohort' },
  'cohorts.notes': { fr: 'Notes (optionnel)', en: 'Notes (optional)' },
  'cohorts.remarks': { fr: 'Remarques...', en: 'Remarks...' },
  'cohorts.nameRequired': { fr: 'Le nom est requis', en: 'Name is required' },
  'cohorts.emailRequired': { fr: "L'email est requis", en: 'Email is required' },
  'cohorts.emailInvalid': { fr: 'Email invalide', en: 'Invalid email' },
  'cohorts.passwordRequired': { fr: 'Mot de passe requis (min. 6 caractères)', en: 'Password required (min. 6 characters)' },
  'cohorts.confirmDelete': { fr: 'Confirmer la suppression', en: 'Confirm Deletion' },
  'cohorts.noCohortYet': { fr: 'Aucune cohorte. Créez votre première cohorte.', en: 'No cohort yet. Create your first cohort.' },
  'cohorts.noStudentsInCohort': { fr: 'Aucun étudiant dans cette cohorte.', en: 'No students in this cohort.' },
  'cohorts.addFirstStudent': { fr: '+ Ajouter le premier étudiant', en: '+ Add the first student' },
  'cohorts.resultsFor': { fr: 'résultat(s) pour', en: 'result(s) for' },
  'cohorts.cannotDelete': { fr: 'Impossible', en: 'Cannot delete' },
  'cohorts.studentsInCohort': { fr: 'étudiant(s) dans cette cohorte', en: 'student(s) in this cohort' },
  'cohorts.importCsv': { fr: 'Importer CSV', en: 'Import CSV' },
  'cohorts.importCsvHint': { fr: "Importer une liste d'étudiants depuis un fichier CSV", en: 'Import a student list from a CSV file' },
  'cohorts.importCount': { fr: 'Importer {n} étudiant(s)', en: 'Import {n} student(s)' },
  'cohorts.csvPreviewTitle': { fr: "Aperçu de l'import", en: 'Import Preview' },
  'cohorts.csvFile': { fr: 'Fichier', en: 'File' },
  'cohorts.csvValid': { fr: 'valide(s)', en: 'valid' },
  'cohorts.csvSkipped': { fr: 'ignoré(s)', en: 'skipped' },
  'cohorts.csvDefaultPassword': { fr: 'Mot de passe par défaut', en: 'Default password' },
  'cohorts.csvPasswordHint': { fr: 'à changer lors de la première connexion', en: 'to be changed on first login' },
  'cohorts.csvFormat': { fr: 'Format attendu : nom,email ou nom,email,cohorte — une ligne par étudiant', en: 'Expected format: name,email or name,email,cohort — one line per student' },
  'cohorts.csvErrorName': { fr: 'Nom manquant', en: 'Missing name' },
  'cohorts.csvErrorDuplicate': { fr: 'Email déjà existant', en: 'Email already exists' },
  'cohorts.defaultCohort': { fr: 'Cohorte par défaut', en: 'Default cohort' },
  'cohorts.toastCohortCreated': { fr: 'Cohorte créée', en: 'Cohort created' },
  'cohorts.toastCohortUpdated': { fr: 'Cohorte mise à jour', en: 'Cohort updated' },
  'cohorts.toastCohortDeleted': { fr: 'Cohorte supprimée', en: 'Cohort deleted' },
  'cohorts.toastStudentAdded': { fr: 'Étudiant ajouté', en: 'Student added' },
  'cohorts.toastStudentUpdated': { fr: 'Étudiant mis à jour', en: 'Student updated' },
  'cohorts.toastStudentDeleted': { fr: 'Étudiant supprimé', en: 'Student deleted' },
  'cohorts.toastPasswordUpdated': { fr: 'Mot de passe mis à jour', en: 'Password updated' },
  'cohorts.toastImported': { fr: 'étudiant(s) importé(s)', en: 'student(s) imported' },
  'cohorts.toastSkipped': { fr: 'ignoré(s)', en: 'skipped' },
  'cohorts.toastError': { fr: 'Une erreur est survenue', en: 'An error occurred' },
  // Assignments page
  'assignments.title': { fr: 'Travaux & Devoirs', en: 'Assignments & Homework' },
  'assignments.subtitle': { fr: 'Scénarios assignés — Programme 2 ERP', en: 'Assigned scenarios — Programme 2 ERP' },
  'assignments.totalAssigned': { fr: 'Total assignés', en: 'Total Assigned' },
  'assignments.completed': { fr: 'Complétés', en: 'Completed' },
  'assignments.pending': { fr: 'En attente', en: 'Pending' },
  'assignments.deadline': { fr: 'Échéance:', en: 'Due:' },
  'assignments.statusCompleted': { fr: 'Complété', en: 'Completed' },
  'assignments.statusPending': { fr: 'En attente', en: 'Pending' },
  'assignments.viewBtn': { fr: 'Voir', en: 'View' },
  'assignments.toastCompleted': { fr: 'Déjà complété', en: 'Already completed' },
  'assignments.toastAccess': { fr: 'Accédez via le Simulateur', en: 'Access via the Simulator' },
  // Modules page extended
  'modules.pedagogicalSlides': { fr: 'slides pédagogiques', en: 'pedagogical slides' },
  'modules.simulationScenarios': { fr: 'scénarios de simulation', en: 'simulation scenarios' },
  'modules.scenariosCompleted': { fr: 'scénarios complétés', en: 'scenarios completed' },
  'modules.programStart': { fr: 'Début du programme', en: 'Program start' },
  'modules.finalSim': { fr: 'ERP-SIM Simulation finale', en: 'ERP-SIM Final Simulation' },
  'modules.viewSlides': { fr: 'Voir les slides', en: 'View Slides' },
  'modules.simulate': { fr: 'Simuler', en: 'Simulate' },
  'modules.programEnd': { fr: 'ERP-SIM Simulation finale', en: 'ERP-SIM Final Simulation' },
  'monitoring.atRisk': { fr: 'En risque', en: 'At Risk' },
  'monitoring.noStudents': { fr: 'Aucun étudiant trouvé', en: 'No students found' },
  // Dashboard extended
  'dashboard.teacherPanel': { fr: 'Suivi des étudiants', en: 'Student Monitoring' },
  'dashboard.systemsStudied': { fr: 'Systèmes étudiés', en: 'Systems studied' },
  'dashboard.sameProcess': { fr: 'Même processus, noms différents', en: 'Same process, different names' },
  'dashboard.nextStep': { fr: 'Prochaine étape recommandée', en: 'Recommended next step' },
  'dashboard.bestScore': { fr: 'Meilleur score : {n}% — à améliorer', en: 'Best score: {n}% — improve it' },
  'dashboard.noActivity': { fr: "Aucune activité pour l'instant. Lancez votre premier scénario !", en: 'No activity yet. Start your first scenario!' },
  'dashboard.scenarioCompleted': { fr: 'Scénario {id} complété', en: 'Scenario {id} completed' },
  'dashboard.viewAll': { fr: 'Voir tout', en: 'View all' },
  'dashboard.completedSub': { fr: 'complétés', en: 'completed' },
  'dashboard.onSims': { fr: 'sur les simulations', en: 'on simulations' },
};


const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Language>(() => {
    return (localStorage.getItem('erp_lang') as Language) || 'fr';
  });

  const setLang = (l: Language) => {
    setLangState(l);
    localStorage.setItem('erp_lang', l);
  };

  const t = (key: string): string => {
    const entry = translations[key];
    if (!entry) return key;
    return entry[lang] || entry['fr'] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLang must be used within LanguageProvider');
  return ctx;
}
